a = ".-"
b = "-..."
c = "-.-."
d = "-.."
e = "."
f = "..-."
g = "--."
h = "...."
i = ".."
j = ".---"
k = "-.-"
l = ".-.."
m = "--"
n = "-."
o = "---"
p = ".--."
q = "--.-"
r = ".-."
s = "..."
t = "-"
u = "..-"
v = "...-"
w = ".--"
x = "-..-"
y = "-.--"
z = "--.."

start = "-.-.-"  # 5
ende = "...-.-."
eins = ".----"
zwei = "..---"
drei = "...--"
vier = "....-"
fuenf = "....."
sechs = "-...."
sieben = "--..."
acht = "---.."
neun = "----."
null = "-----"

dollar_zeichen = "...-..-"  # 7
minus = "-....-"  # 6
punkt = ".-.-.-"  # 6
komma = "--..--"  # 6
frage_zeichen = "..--.."  # 6
ausrufe_zeichen = "-.-.--"  # 6
doppel_punkt = "---..."  # 6
semi_colon = "-.-.-."  # 6
klammer_zu = "-.--.-"  # 6
unter_strich = "..--.-"  # 6
anfuehrungs_zeichen = ".-..-."  # 6
at_zeichen = ".--.-."  # 6
plus = ".-.-."  # 5
slash = "-..-."  # 5
gleich_zeichen = "-...-"  # 5
klammer_auf = "-.--."  # 5
und_zeichen = ".-..."  # 5
